#!/usr/bin/env python3
"""Pack SproutScore public data into compact JS modules for the MCP worker.

Reads (source of truth, never modified):
  ~/workspace/sproutscore/data/centers.json
  ~/workspace/sproutscore/data/violation-translations.json

Writes (generated, checked in so the worker deploy is self-contained):
  src/data.js   - per-center compact aggregates (top violation codes only,
                  full decode text resolved at request time)
  src/codes.js  - trimmed translation table (plain_english, severity, family,
                  tour question, category; status text templated at runtime)

Re-run any time the source bundles change:
  python3 pack.py

Design notes:
- Centers are stored as positional arrays (see COLS) to minimize bytes.
- Per-center violations are deduplicated to one entry per distinct
  (code, date, category, status) row -> [code, citations, dates, category, statuses].
- Full per-citation decode text lives ONLY in src/codes.js.
"""
import json
import os
import re

BASE = os.path.expanduser("~/workspace/sproutscore/data")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src")

CAT_RANK = {"PUBLIC HEALTH HAZARD": 0, "CRITICAL": 1, "GENERAL": 2}
CAT_OF_RANK = {v: k for k, v in CAT_RANK.items()}


def js_escape(s):
    return json.dumps(s, ensure_ascii=False)


def main():
    with open(os.path.join(BASE, "centers.json"), encoding="utf-8") as f:
        centers_bundle = json.load(f)
    with open(os.path.join(BASE, "violation-translations.json"), encoding="utf-8") as f:
        trans = json.load(f)

    meta = centers_bundle["meta"]
    tmeta = trans["meta"]

    total_inspections = sum(ce["inspections"] for ce in centers_bundle["centers"])
    total_flagged = sum(ce["flagged"] for ce in centers_bundle["centers"])

    # ---- src/data.js ----
    center_rows = []
    for ce in centers_bundle["centers"]:
        # aggregate violations: one entry per distinct (code,date,cat,status)
        agg = {}
        for v in ce.get("violations", []):
            key = (v["code"], v["date"], v["city_category"], v["status"])
            agg[key] = agg.get(key, 0) + 1
        # collapse to per-code: citations, sorted unique dates, worst category, statuses
        per_code = {}
        for (code, date, cat, status), n in agg.items():
            e = per_code.setdefault(code, {"n": 0, "dates": set(),
                                           "cat": "GENERAL", "statuses": set()})
            e["n"] += n
            e["dates"].add(date)
            e["statuses"].add(status)
            if CAT_RANK.get(cat, 9) < CAT_RANK.get(e["cat"], 9):
                e["cat"] = cat
        viol = []
        for code, e in per_code.items():
            viol.append([code, e["n"], sorted(e["dates"]), e["cat"],
                         sorted(e["statuses"])])
        viol.sort(key=lambda x: (-x[1], x[0]))

        center_rows.append([
            ce["center_id"],
            ce["name"],
            ce["borough"],
            ce["address"],
            ce["zipcode"],
            ce.get("child_care_type", ""),
            ce["inspections"],
            ce["flagged"],
            ce.get("last_inspection", ""),
            ce.get("city_violation_rate_pct", 0),
            viol,
        ])

    data_meta = {
        "data_as_of": meta["data_as_of"],
        "data_window": meta["data_window"],
        "source": meta["source"],
        "centers": meta["centers"],
        "inspections": total_inspections,
        "flagged_inspections": total_flagged,
        "cohort_avg_violation_rate_pct": meta["cohort_avg_violation_rate_pct"],
        "global_flagged_rate_pct": meta["global_flagged_rate_pct"],
        # positional column contract for center rows
        "cols": ["center_id", "name", "borough", "address", "zipcode",
                 "child_care_type", "inspections", "flagged",
                 "last_inspection", "city_violation_rate_pct", "violations"],
        # positional column contract for violation rows
        "viol_cols": ["code", "citations", "dates", "city_category", "statuses"],
    }

    with open(os.path.join(OUT, "data.js"), "w", encoding="utf-8") as f:
        f.write("// GENERATED by pack.py - do not edit by hand. Re-run pack.py to regenerate.\n")
        f.write("export const DATA_META = " + js_escape(data_meta) + ";\n")
        f.write("export const CENTERS = " + js_escape(center_rows) + ";\n")

    # ---- src/codes.js ----
    codes = {}
    for code, e in trans["codes"].items():
        sb = e.get("status_breakdown", {})
        codes[code] = [
            e.get("plain_english", ""),
            e.get("severity", "minor"),
            e.get("family", ""),
            e.get("tour_question", ""),
            e.get("city_category_max", "GENERAL"),
            int(sb.get("CORRECTED", 0)),
            int(sb.get("OPEN", 0)),
        ]
    families = {}
    for fam, e in trans["families"].items():
        families[fam] = [
            e.get("label", ""),
            e.get("tour_question", ""),
            int(e.get("codes", 0)),
        ]
    code_meta = {
        "data_as_of": tmeta["data_as_of"],
        "data_window": tmeta["data_window"],
        "review_status": "AI_SEEDED_PENDING_HUMAN_REVIEW",
        "review_note": ("plain_english decodes are AI-seeded and pending human "
                        "review - not expert-verified."),
        "severity_tiers": tmeta["severity_tiers"],
        "status_meanings": tmeta["status_meanings"],
        # positional column contracts
        "code_cols": ["plain_english", "severity", "family", "tour_question",
                      "city_category_max", "corrected_citywide", "open_citywide"],
        "family_cols": ["label", "tour_question", "codes"],
    }
    with open(os.path.join(OUT, "codes.js"), "w", encoding="utf-8") as f:
        f.write("// GENERATED by pack.py - do not edit by hand. Re-run pack.py to regenerate.\n")
        f.write("export const CODE_META = " + js_escape(code_meta) + ";\n")
        f.write("export const CODES = " + js_escape(codes) + ";\n")
        f.write("export const FAMILIES = " + js_escape(families) + ";\n")

    for name in ("data.js", "codes.js"):
        p = os.path.join(OUT, name)
        print(f"{name}: {os.path.getsize(p):,} bytes")


if __name__ == "__main__":
    main()
